### PR TITLE
Enable terms of service checkbox on registration

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd

### CODE REVIEW

**Comment by stvstnfrd** [comment]
This seems reasonable, though I'm not sure how this was apparently working earlier when we were testing.. Can you shed any light on what happened?

**Comment by caesar2164** [comment]
nope, no idea...

**Comment by stvstnfrd** [comment]
@caesar2164 Before merging, we need to verify that this is _only_ used by logistration and _not_ also by old login+register..

**Comment by caesar2164** [comment]
cherry-picked into RC

**Pull request closed without merging**
