### PR TITLE
Remove USE_CME_REGISTRATION flag

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by caesar2164** [comment]
the end of an era! 👍

**Comment by stvstnfrd** [comment]
This should wait for https://github.com/Stanford-Online/edx-platform/pull/744

**Comment by stvstnfrd** [comment]
Actually, I think we can go ahead and remove this regardless of Stanford-Online/edx-platform#744
since that flag will just default to False anyway.

@dcadams Any objection here?

**Comment by stvstnfrd** [comment]
Note: the test failure is just the flaky pip install error and can be ignored.

**Pull request merged**
