### PR TITLE
Merge configuration form upstream

### PR DESCRIPTION
**Pull request by stvstnfrd**
Merged from: a62eb70bb070aeb6044c2bf53a0bd19a5e73f438

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams @caesar2164 We should try using this in the next deploy.

**Comment by caesar2164** [comment]
cool, that looks pretty useful!

**Comment by stvstnfrd** [comment]
@caesar2164 Let's do any sandbox work off of this branch.

**Comment by caesar2164** [comment]
K, sounds good!

**Comment by stvstnfrd** [comment]
After we merge the release, I'm going to test this by doing a normal stage deploy of `origin/master`.

**Comment by stvstnfrd** [comment]
Closing in favor of #53

**Pull request closed without merging**
