### PR TITLE
[Merge with Platform merge past Feb 2016] Add PARTNER_SUPPORT_EMAIL in default FEATURES

### PR DESCRIPTION
**Pull request by caesar2164**
PARTNER_SUPPORT_EMAIL gets used to display contact email for Studio support

@stvstnfrd - pulling in upstream change.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
Don't we also need the platform change?

**Comment by caesar2164** [comment]
This setting is not used in our codebase yet.

Before merging this PR wait until we get a successful merge from upstream.
Then cherry-pick this commit: https://github.com/edx/edx-platform/commit/ce769b363dd77e4780cb929be3443569db12ddd6

**Comment by stvstnfrd** [comment]
@caesar2164 Should this be merged now?

**Comment by caesar2164** [comment]
Sure @stvstnfrd, I forgot all about this PR...

**Comment by stvstnfrd** [comment]
me too :O

**Comment by caesar2164** [comment]
I'll rebase and do the cherry pick as the above comment says

**Comment by stvstnfrd** [comment]
@caesar2164 What's up with this?

**Comment by caesar2164** [comment]
this got cherry-picked at some point, I'll close it.

**Pull request closed without merging**
