### PR TITLE
Bump Stanford devstack to Ficus

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@kluo @caesar2164 Can you try spinning up a stack w/ this `Vagrantfile`?
We should be working off of this base now.

Also freaky, look at the dates!

**Comment by caesar2164** [comment]
crazy talk

**Comment by caesar2164** [comment]
👍

**Comment by stvstnfrd** [comment]
@caesar2164 Have you tested this though?
I don't want to merge until someone else has confirmed it working locally.

**Comment by caesar2164** [comment]
W00t! Devstack booted up and everything! 👍

**Pull request merged**
