### PR TITLE
Consolidate user plays

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dcadams @caesar2164

**Comment by caesar2164** [comment]
@stvstnfrd - where is `{{env}}` set?

**Comment by stvstnfrd** [comment]
@caesar2164 It's passed in when we invoke ansible. It's handled via the deploy scripts:

```shell
ansible-playbook -e "machine=(app(1|2)|util(1|2)|jenkins) env=prod"
```

**Comment by caesar2164** [comment]
ah ok, just wanted to make sure that was always passed in. cool, :+1:

**Pull request merged**
