### PR TITLE
Create analytics api playbooks for suclass

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
This replaces #29 

@dcadams

**Comment by dcadams** [comment]
:+1:

**Comment by stvstnfrd** [comment]
I can't remember what this was; what about you @dcadams @dylanrhodes ?

**Comment by stvstnfrd** [comment]
@dylanrhodes I don't _think_ we need this, given that our playbooks should now be parameterized to support multiple deployments. I'm going to close it, but we can reopen, if necessary.

**Pull request closed without merging**
