### PR TITLE
Variable defaults for elasticsearch role

### PR DESCRIPTION
**Pull request by felipemontoya**
Adding some defaults so that the configuration template renders in devstack mode

### CODE REVIEW

**Comment by felipemontoya** [comment]
Just saw PR#135. I believe that would also fix this issue

**Comment by stvstnfrd** [comment]
@felipemontoya Thanks for catching this!

I made a few more tweaks to actually remove `Cluster`/`Deployment` and move them into our "internal" playbooks; that's over in #138 . I think I'd prefer to merge #138 over this, assuming it does the trick.

Take a look and let me know if that works for you.

**Comment by stvstnfrd** [comment]
@felipemontoya I'm not sure that #135 would fix this.

The problem is the undefined variable(s) used by the elasticsearch role. While #135 does make the Logstash and Kibana optional, the elasticsearch role is still run regardless, since it's needed by the default devstack.

I just kicked off a new devstack build that includes both #138 and #135. Assuming that passes, I'll merge them both.

**Comment by felipemontoya** [comment]
I like #138 the most. It fixes the problem we were having, and it is the cleanest. I'll close this favoring that.

**Pull request closed without merging**
